export const CONFIG = {
  STORAGE: {
    SESSION: 'SESSION',
    PERMISSIONS: 'PERMISSIONS',
    ACCESOS: 'ACCESOS',
    TRANSLATIONS: 'TRANSLATIONS',
    TRANSLATION_CHECKSUM: 'TRANSLATION_CHECKSUM',
    LAST_LANGUAGE: 'LAST_LANGUAGE'
  },
}
